# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, free, hoopl, hspec, hspecExpectations, lensFamilyCore
, linearscan, transformers, cabalInstall
}:

cabal.mkDerivation (self: {
  pname = "linearscan-hoopl";
  version = "0.1.0.0";
  src = builtins.filterSource (path: type: type != "unknown") ./.;
  buildTools = [ cabalInstall ];
  buildDepends = [ free hoopl linearscan transformers ];
  testDepends = [
    hspec hspecExpectations lensFamilyCore linearscan transformers
  ];
  meta = {
    homepage = "http://github.com/jwiegley/linearscan-hoopl";
    description = "Make it easy to use the linearscan register allocator with Hoopl";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
